### ISSUE TITLE
Two lines in each entry

### ISSUE THREAD

**Issue by DiomedesDominguez** [SuavePirate/SuaveControls.MaterialFormControls#19]
I'm getting two bottom lines on each entry. I'm using the latest version from nuget.

![captura de pantalla 2018-02-08 a la s 10 39 20](https://user-images.githubusercontent.com/4379316/35978560-73a9549a-0cbc-11e8-90c0-a4cc60d8e537.png)

**Comment by SuavePirate** [comment]
Woah. Never seen that before. Did you initialize the `BorderlessEntryRenderer` in your `MainActivity` and `AppDelegate`?

**Comment by DiomedesDominguez** [comment]
You were right, it was missing ```SuaveControls.MaterialForms.Android.RendererInitializer.Init();``` in the MainActivity class.
