### ISSUE TITLE
DatePicker and TimePicker not working on iOS

### ISSUE THREAD

**Issue by yuv4ik** [SuavePirate/SuaveControls.MaterialFormControls#2]
Hello,

It seems like the DatePicker and TimePicker not working as expected on iOS 11.0 and 9.3.
By 'not working as expected' I mean that it's not showing the pickers and it seems like the focus trick is not working properly.

Check the GIF: https://giphy.com/gifs/xT9Igr4nDwTesDlw0U

Seems like the solution is quite simple:
Device.BeginInvokeOnMainThread(() =>
{
    EntryField.Unfocus();
    Picker.Focus();
});

Have to ensure focus related stuff execution on the Main thread.

I created a [pull request](https://github.com/SuavePirate/SuaveControls.MaterialFormControls/pull/3).

**Comment by SuavePirate** [comment]
Thanks for finding this and resolving it yourself!
