### ISSUE TITLE
MaterialButton is missing

### ISSUE THREAD

**Issue by DiomedesDominguez** [SuavePirate/SuaveControls.MaterialFormControls#20]
In the latest version of the nuget package is missing the [suave:MaterialButton](https://github.com/SuavePirate/MaterialButton).

![captura de pantalla 2018-02-08 a la s 11 00 29](https://user-images.githubusercontent.com/4379316/35979675-5356952e-0cbf-11e8-8282-05af3f18a224.png)

**Comment by SuavePirate** [comment]
Yeah, it was never in the nuget package. I'll add it as a feature request.

**Comment by SuavePirate** [comment]
Now included in latest prerelease package https://www.nuget.org/packages/MaterialFormControls/2018.2.22-pre1
