### ISSUE TITLE
Shadow doesn't respect border radius property on button

### ISSUE THREAD

**Issue by gbreen12** [SuavePirate/SuaveControls.MaterialFormControls#24]
I'm trying to create a round button but the shadow remains a square around the button. I realize there is another project for this kind of thing (FloatingActionButton), I'm just thinking I could use the material button with a border radius (whatever that is) and the shadow can adjust accordingly.

**Comment by SuavePirate** [comment]
Can you attach a screenshot?

**Comment by gbreen12** [comment]
![simulator screen shot - iphone x - 2018-03-01 at 17 10 00](https://user-images.githubusercontent.com/3309528/36876712-822f9ee4-1d73-11e8-8552-9b7910f05d9e.png)
