### ISSUE TITLE
Borderless Entry has border but does not contain the Init() method

### ISSUE THREAD

**Issue by KaizerT** [SuavePirate/SuaveControls.MaterialFormControls#31]
XF Version: 2.5.0.121934
PCL Profile: Profile 111
MaterialFormControls Version: 2018.2.22-pre1

Hello,

I'm trying to use the material entry in your blog post. I ended up downloading the whole library just so I have the rest of the controls available. The premise is great but I have not been able to use the material entry since the borderless entry still has a border, and trying to call BorderlessEntry.Init() causes an error since the method does not exist. After digging around in the example I saw that it was supposed to be RendererInitializer.Init() which seems to be a child of SuaveControls.MAterialForms.Android which is not included in the nuget package.

**Comment by SuavePirate** [comment]
You need to call that in the platform specific code like in your `MainActivity` for Android.

**Comment by KaizerT** [comment]
@SuavePirate I did check the platform specific code, and in your example you reference MaterialForms.Android in your Main Activity, however this namespace does not exist in the nuget package. I checked the Object Explorer and only MaterialForms.IOS exists.

**Comment by SuavePirate** [comment]
sounds like you just installed that on iOS.

**Comment by KaizerT** [comment]
I installed it in all the projects, would you like a screenshot?

![image](https://user-images.githubusercontent.com/37116136/39163532-8f99dfda-4740-11e8-8891-cdc202788f0a.png)

![image](https://user-images.githubusercontent.com/37116136/39163542-9f31a662-4740-11e8-9527-01f95af2188b.png)

**Comment by SuavePirate** [comment]
Was the install fully successful

**Comment by KaizerT** [comment]
Yes.

**Comment by SuavePirate** [comment]
So in your MainActivity you can't reference `using SuaveControls.MaterialForms.Android.Renderers`? I just installed this in a new project and was able to reference it.

**Comment by KaizerT** [comment]
Yeah and I can't see it in the package anywhere. It's like it was just left out.

**Comment by SuavePirate** [comment]
Then the install wasn't fully successful

**Comment by KaizerT** [comment]
I just saw the issue, mono android had to be version 8 and I had mine set as 7.
