### ISSUE TITLE
Hidden Label offset is way too far from the actual control

### ISSUE THREAD

**Issue by KaizerT** [SuavePirate/SuaveControls.MaterialFormControls#32]
Hi,

I was able to install the package and I noticed that the label is way too far from the entry when the entry has focus. I'm guessing the code is the same for similar controls. The label reaches the control directly above the entry when added to a stack layout. I implemented my own version of the material entry from your blog post and found that instead of using the entry height as the y-axis offset I used 30% of the entry height.

**Comment by SuavePirate** [comment]
Would you be willing to attach screenshots and/or submit a PR with an update for this?

**Comment by marcodafonseca** [comment]
I have this same issue
![image](https://user-images.githubusercontent.com/7070154/41576304-f205fcf4-7386-11e8-879a-635222a48a6f.png)

**Comment by marcodafonseca** [comment]
Also, I realize my previous screenshot doesn't show it very well, but I'm also getting a 2nd border line underneath the one that I'm expecting to be there... Any idea why this might be happening?

**Comment by SuavePirate** [comment]
This sounds like a renderer is missing. Which would explain why the label jumps so high. Looks like the `BorderlessEntryRenderer` is not working. What version of Xamarin.Forms are you using? I've seen some issues with 3.0 for some of the renderers being booted

**Comment by marcodafonseca** [comment]
I am using version 3.0.0.561731

Is there a known work-around for this version that I could use?

**Comment by marcodafonseca** [comment]
I upgraded to Xamarin.Forms 3.1.x and it sorted itself out
![image](https://user-images.githubusercontent.com/7070154/41810098-fa6b5c48-76f8-11e8-960e-2d1604e94fda.png)

**Comment by SuavePirate** [comment]
This seems to have been an issue with 3.0.x with certain types of custom renderers not making it through the linking and build process. This would have caused the height jump since the original Entry has a much larger height. Closing now since the workaround is to upgrade or downgrade xamarin.forms
