### ISSUE TITLE
Nuget package is not availalbe

### ISSUE THREAD

**Issue by yuv4ik** [SuavePirate/SuaveControls.MaterialFormControls#4]
Hello,

I really like your solution and I would like to reuse it in my projects, however it seems like it is not packed as a nuget package. Do you plan to release a nuget package? Otherwise it might be not that convenient to use it.

P.S.: Thanks for the great work!

**Comment by SuavePirate** [comment]
That is in the plans! There is an issue I need to resolve with iOS, then will be publishing it.

Check out my recent blog post on some of the other libraries I'm publishing soon! I appreciate the support ☺

https://alexdunn.org/2017/09/25/xamarin-nuget-coming-to-a-nuget-package-near-you/

**Comment by Im-PJ** [comment]
Any plans yet?

**Comment by SuavePirate** [comment]
Bam! https://www.nuget.org/packages/MaterialFormControls/2018.1.18-pre1

**Comment by SuavePirate** [comment]
Note, this does NOT include UWP. I only have a mac right now to work off of, so I couldn't reference the UWP project in the NuGet package project. If someone else wants to help with adding the uwp project, that would be great. If not, it will have to wait until I fix my windows desktop
