### ISSUE TITLE
MaterialPicker enhancements 

### ISSUE THREAD

**Issue by yuv4ik** [SuavePirate/SuaveControls.MaterialFormControls#6]
Would be nice if the MaterialPicker will:

1.  Support a generic list for ItemsSource, currently it supports only strings
2. Will have 'SelectedItemProperty' bindable property
3. Will have 'SelectedIndexChanged' event

P.S.: I will try to contribute and help with this list.

**Comment by SuavePirate** [comment]
Good call! And appreciate the help before we put this on nuget.

**Comment by SuavePirate** [comment]
Looks like this is working well now with your latest changes.
