### ISSUE TITLE
[Issue] MaterialDatePicker| Android | Today's Date not working

### ISSUE THREAD

**Issue by welcometoall** [SuavePirate/SuaveControls.MaterialFormControls#9]
If I select today’s date in Android, It is showing as empty. So I need to select another date and then select today’s date.

Steps:
1. If DatePicker is clicked, It popup with selected as today's date. Click Ok.
2. It is not firing "Picker_DateSelected".

**Comment by yuv4ik** [comment]
Behaves the same way on iOS.

**Comment by SuavePirate** [comment]
The latest changes from @welcometoall seems to fix this issue, however, there is no way to remove the date. This is how it also behaves in the default `DatePicker`, but perhaps we should add some sort of cancel or remove button to support nullable dates. Just some thoughts.
